/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/media': RouteRecordInfo<'/media', '/media', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/photos': RouteRecordInfo<'/photos', '/photos', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/11-1.VChart主题相关概念': RouteRecordInfo<'/posts/11-1.VChart主题相关概念', '/posts/11-1/VChart主题相关概念', Record<never, never>, Record<never, never>>,
    '/posts/11-2VChart主题更新机制': RouteRecordInfo<'/posts/11-2VChart主题更新机制', '/posts/11-2VChart主题更新机制', Record<never, never>, Record<never, never>>,
    '/posts/12-1.VChart插件机制': RouteRecordInfo<'/posts/12-1.VChart插件机制', '/posts/12-1/VChart插件机制', Record<never, never>, Record<never, never>>,
    '/posts/12-2.VChart插件功能源码详解': RouteRecordInfo<'/posts/12-2.VChart插件功能源码详解', '/posts/12-2/VChart插件功能源码详解', Record<never, never>, Record<never, never>>,
    '/posts/2-1.VTable场景树概念': RouteRecordInfo<'/posts/2-1.VTable场景树概念', '/posts/2-1/VTable场景树概念', Record<never, never>, Record<never, never>>,
    '/posts/2-2.VTable元素与场景树的表达关系': RouteRecordInfo<'/posts/2-2.VTable元素与场景树的表达关系', '/posts/2-2/VTable元素与场景树的表达关系', Record<never, never>, Record<never, never>>,
    '/posts/2-3.VTable场景树渲染': RouteRecordInfo<'/posts/2-3.VTable场景树渲染', '/posts/2-3/VTable场景树渲染', Record<never, never>, Record<never, never>>,
    '/posts/2-4.VTable不同图元类型渲染流程': RouteRecordInfo<'/posts/2-4.VTable不同图元类型渲染流程', '/posts/2-4/VTable不同图元类型渲染流程', Record<never, never>, Record<never, never>>,
    '/posts/2-5.VTable场景树的更新': RouteRecordInfo<'/posts/2-5.VTable场景树的更新', '/posts/2-5/VTable场景树的更新', Record<never, never>, Record<never, never>>,
    '/posts/2-6.VTable的渐进式加载': RouteRecordInfo<'/posts/2-6.VTable的渐进式加载', '/posts/2-6/VTable的渐进式加载', Record<never, never>, Record<never, never>>,
    '/posts/2023年度总结': RouteRecordInfo<'/posts/2023年度总结', '/posts/2023年度总结', Record<never, never>, Record<never, never>>,
    '/posts/2024年度总结': RouteRecordInfo<'/posts/2024年度总结', '/posts/2024年度总结', Record<never, never>, Record<never, never>>,
    '/posts/工作中如何管理git账号': RouteRecordInfo<'/posts/工作中如何管理git账号', '/posts/工作中如何管理git账号', Record<never, never>, Record<never, never>>,
    '/posts/神奇的插件Code Inspector是如何工作的？': RouteRecordInfo<'/posts/神奇的插件Code Inspector是如何工作的？', '/posts/神奇的插件Code Inspector是如何工作的？', Record<never, never>, Record<never, never>>,
    '/posts/手机APP会在后台窃听我说话并且对此针对性投放广告？': RouteRecordInfo<'/posts/手机APP会在后台窃听我说话并且对此针对性投放广告？', '/posts/手机APP会在后台窃听我说话并且对此针对性投放广告？', Record<never, never>, Record<never, never>>,
    '/posts/Javascript深入理解': RouteRecordInfo<'/posts/Javascript深入理解', '/posts/Javascript深入理解', Record<never, never>, Record<never, never>>,
    '/posts/Nestjs': RouteRecordInfo<'/posts/Nestjs', '/posts/Nestjs', Record<never, never>, Record<never, never>>,
    '/posts/web-performance-metrics': RouteRecordInfo<'/posts/web-performance-metrics', '/posts/web-performance-metrics', Record<never, never>, Record<never, never>>,
    '/posts/wujie保活模式+预渲染带来的问题和解决手段': RouteRecordInfo<'/posts/wujie保活模式+预渲染带来的问题和解决手段', '/posts/wujie保活模式+预渲染带来的问题和解决手段', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/use': RouteRecordInfo<'/use', '/use', Record<never, never>, Record<never, never>>,
  }
}
